version: '3.8'

services:
  phish:
    container_name: phish
    image: phish
    build: .
    command: ["python", "-m", "uvicorn", "phishtank.app:app", "--reload", "--host", "0.0.0.0"]
    volumes:
      - ./:/app:z
    ports:
      - "8000:8000"
    environment:
      - PHISHTANK_USERNAME=$PHISHTANK_USERNAME
